### PR TITLE
Add support for the error callback

### PR DESCRIPTION
**Pull request by aib**
I've done some preliminary work on adding the error callback as per #6.

### CODE REVIEW

**Comment by SpotlightKid** [comment]
Thanks for the PR. I had a superficial look at it and it looks good. I'll do a proper review asap and then hopefully merge it. If you come up with tests in the meantime, that would make this even easier ;)

**Comment by aib** [comment]
An issue I came across is that the error callback isn't always called. I tracked it down to an upstream bug in rtmidi: https://github.com/thestk/rtmidi/pull/87
An small fix in RtMidi.cpp, but I didn't want to touch it here in this repo.

Another is the error message coming as <class 'bytes'>; an artifact of the std::string conversion. I wasn't sure whether to leave it as is or attempt a 'str' conversion (and whether to use a Python 2 or 3 'str' for that matter). There were two relevant snippets in the get_port_name() methods, but I didn't want to create yet another copy. I think it might be a better idea to refactor the conversion. I'm ready to test the "else" part, being on Linux :)

**Comment by SpotlightKid** [comment]
I refactored the Cython wrapper hierarchy classes to better match the underlying C++ classes and to remove some code duplication in 3a18280.

This means you have to rebase and adapt your PR and you can use `MidiBase._decode_string` to convert the error message.

**Comment by SpotlightKid** [comment]
I also updated `RtMidi.cpp/.h` to the latest version from upstream and applied the patch from thestk/rtmidi#87 you mentioned above.

**Pull request closed without merging**
