### PR TITLE
Build wheels using cibuildwheel

### PR DESCRIPTION
**Pull request by Czaki**
This PR adds building wheels using [cibuildwheel](https://github.com/pypa/cibuildwheel/) which simplifies creating wheels and adds support for Linux wheels. It also changes macOS wheels from x86_64 to universal2 (to work on m1 machine). 

I do not found an option to run tests on CI.

Here sample run https://github.com/Czaki/python-rtmidi/actions/runs/1253787788

### CODE REVIEW

**Comment by SpotlightKid** [comment]
Many thanks for the PR. I'll be on holiday next week and hop to to find the time to have a look at it then. Thanks for your work and patience.

**Comment by ntamas** [comment]
@SpotlightKid Did you have a chance to look at this PR? It would be great to have a new set of wheels on PyPI as Python 3.10 has been released; also, I currently need to compile from source on Apple Silicon. Thanks a lot!

**Comment by SpotlightKid** [comment]
@ntamas Not in detail yet, sorry. I'm away for the weekend, but I'll try to look at it next week. At first glance it looks good, though.

**Comment by ntamas** [comment]
Thanks! In the meanwhile I tried the PR In my own fork and it seems like it still works nicely and generates correct wheels for Win32, macOS and Linux; see [here](https://github.com/ntamas/python-rtmidi/actions/runs/1544687352).

**Comment by Czaki** [comment]
Just updated to the last release of cibuildwheel.
Disable musllinux wheels as it fails to detect pthread. I do not know if this check should be performed on musllinux (it may be built-in muslc).

**Comment by Bubobubobubobubo** [comment]
@SpotlightKid: can we proceed further with the integration of `cibuildwheel`? 
This would greatly simplify the installation process of many `rtmidi` dependant code bases.

**Comment by georgeharker** [comment]
I'd love to see this in mainline - it fixes issues building for python 3.11

**Comment by brunoenten** [comment]
Thanks for your contribution. It was probably used to create PR https://github.com/SpotlightKid/python-rtmidi/pull/119, superseding this one.

**Comment by Czaki** [comment]
As last time I check the #119 was failing so I kept it to make some wheel available for some folks. 

If you need help with cibuildwheel feel free to ping

**Comment by brunoenten** [comment]
True but it was superseded by https://github.com/SpotlightKid/python-rtmidi/pull/121 which fixed the cibuildwheel that remained.
Both PR clearly used your work as a basis, so thanks for your contribution!

**Pull request closed without merging**
