### PR TITLE
Add support for automatically building Windows / OSX wheels using AppVeyor / Travis CI

### PR DESCRIPTION
**Pull request by benoit-pierre**
Build wheels for:
- Windows: 32bits and 64bits variants for Python 2.7, 3.5, 3.6, and 3.7
- macOS: Python 2.7, 3.6, and 3.7

Those are automatically uploaded to PyPI.

`TWINE_USERNAME` and `TWINE_PASSWORD` must be set in each project settings (don't forget to toggle encryption for `TWINE_PASSWORD` on AppVeyor!).

The builds are started on tag only (but the tag name itself does not matter): at first I added support for running the tests, but most of them fail because of the lack of MIDI devices: `RuntimeError: MidiOutCore::openPort: no MIDI output destinations found!`.

### CODE REVIEW

**Comment by benoit-pierre** [comment]
Amended to use the `release` alias.

**Comment by SpotlightKid** [comment]
Thank you for contribution this. This is something that I would have liked to myself much sooner. I tried running the tests on Travis some time ago, but since they do not include the necessary kernel modules in their Linux images, which thus have no ALSA or JACK support, the tests won't work and I abandoned the effort.

I would like to test the wheel building and uploading on a special branch and with https://test.pypi.org (I have an account there too), but I'm not sure how to approach this. Can you help with this?

**Comment by SpotlightKid** [comment]
My username on  `test.pypi.org` is `strogon14`.

**Comment by benoit-pierre** [comment]
OK, I've added you as a owner, so you can remove me from the project (I can't do it myself).

**Comment by benoit-pierre** [comment]
I tweaked the builds so the wheels created are reproducible (assuming contents are unchanged).

**Comment by SpotlightKid** [comment]
I've now pushed 1.1.2, which is the first public release to use this new facility.

A huge thanks for this contribution, Benoit. This is a big improvement of the project.

**Pull request merged**
